es_cluster_name: graylog
# es_node_name: "{{ inventory_hostname }}"
es_api_port: 9200
es_http_port: 9200
es_transport_tcp_port: 9300
# es_api_host: "{{ inventory_hostname }}"
es_major_version: 5.x
es_version: 5.5.0
es_use_repository: true
es_version_lock: true
es_install_java: true
es_heap_size: 256m
# es_discovery_zen_ping_unicast_hosts: "{{ groups['elasticsearch'] | map('extract', hostvars, 'ansible_nodename') | list }}"
