es_cluster_name: graylog
# es_node_name: "{{ inventory_hostname }}"
es_instance_name: "{{ inventory_hostname }}"
es_api_port: 9200
es_http_port: 9200
es_transport_tcp_port: 9300
# es_api_host: "{{ inventory_hostname }}"
es_major_version: 5.x
es_version: 5.5.0
es_use_repository: true
es_version_lock: true
es_install_java: true
es_heap_size: 256m
es_config: {
  cluster.name: "{{ es_cluster_name }}",
  #  es.instance.name: "{{ inventory_hostname }}",
  http.port: "{{ es_http_port }}",
  network.host: 0.0.0.0,
  network.publish_host: "_enp0s8:ipv4_",
  transport.tcp.port: "{{ es_transport_tcp_port }}",
  discovery.zen.ping.unicast.hosts: "{{ groups['elasticsearch'] | map('extract', hostvars, 'ansible_nodename') | list }}",
  # gateway.expected.nodes: "{{ groups['elasticsearch'] | map('extract', hostvars, 'ansible_nodename') | count }}",
  node.data: true,
  node.master: true,
}
# es_discovery_zen_ping_unicast_hosts: "{{ groups['elasticsearch'] | map('extract', hostvars, 'ansible_nodename') | list }}"
