---
mongodb_hosts_group: mongodb

mongodb_version: 3.2
mongodb_full_version: 3.2.2

mongodb_metrics: False
mongodb_dependencies: ""

mongodb_log_dir: /var/log/mongodb
mongodb_database_dir: /var/lib/mongo
mongodb_system_user: mongod
mongodb_system_group: mongod
mongdb_pidfilepath: /var/run/mongodb/mongod.pid

mongodb_admin_user: "{{ fh_mongodb_admin_user | default('admin')}}"
mongodb_admin_password: "{{ fh_mongodb_admin_password | default('password')}}"

mongodb_interface: "{{ fh_mongodb_interface | default(ansible_default_ipv4.interface) }}"
mongodb_address: "{{ hostvars[inventory_hostname]['ansible_' + mongodb_interface]['ipv4']['address'] }}"
mongodb_port: "{{ fh_mongodb_port | default('27017') }}"

mongodb_replica_name: "{{ fh_mongodb_replica_name | default('rs0')}}"
mongodb_replica_arbiter:
mongodb_replica_primary_node: "{{ groups[mongodb_hosts_group][0]['ansible_' + mongodb_interface]['ipv4']['address'] }}"
mongodb_replica_secondary_nodes: "{{ groups[mongodb_hosts_group][1:]['ansible_' + mongodb_interface]['ipv4']['address'] | list }}"

# PLAIN
# MONGODB-CR
# SCRAM-SHA-1
#mongodb_authentication: SCRAM-SHA-1
#mongodb_authentication: MONGODB-CR

mongodb_create_users: true
# mongodb_users: {}
mongodb_users:
  graylog:
    name: "{{ fh_graylog_mongodb_user | default('graylog')}}"
    pass: "{{ fh_graylog_mongodb_pass | default('password')}}"
    db: "{{ fh_graylog_mongodb_database | default('graylog')}}"
    roles: readWrite,dbAdmin


mongodb_exporter_version: "1.0.0"

mongodb_exporter_url: "https://github.com/dcu/mongodb_exporter/releases/download/v{{ mongodb_exporter_version }}/mongodb_exporter-linux-amd64"
mongodb_exporter_release_name: "mongodb_exporter-linux-amd64"

mongodb_exporter_root_dir: "/opt/mongodb_exporter"
mongodb_exporter_dist_dir: "{{ mongodb_exporter_root_dir }}/dist"
mongodb_exporter_bin_dir: "{{ mongodb_exporter_root_dir }}/current"

mongodb_exporter_pid_path: "/var/run/mongodb_exporter.pid"
mongodb_exporter_log_dir: "/var/log/mongodb_exporter"
mongodb_exporter_log_file: "{{ mongodb_exporter_log_dir }}/mongodb_exporter.log"

mongodb_exporter_service_name: mongodb_exporter
mongodb_exporter_web_listen_address: "0.0.0.0:9001"

# Mongodb URI, format: [mongodb://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options] (default "mongodb://localhost:27017")

mongodb_exporter_web_metrics: '/metrics'
mongodb_exporter_config_flags:
  'web.listen-address': '{{ mongodb_exporter_web_listen_address }}'
  'mongodb.uri': 'mongodb://{{ mongodb_address }}:{{ mongodb_port }}'
  'web.metrics-path': '{{ mongodb_exporter_web_metrics }}'
  'log_dir': '{{ mongodb_exporter_log_dir }}'

## misc
common_pip_packages:
  pymongo:
    name: pymongo
    version: "{{ mongodb_full_version }}"
