---
- name: yum_makecache
  command: yum makecache

#  - name: 'YUM - fire and forget task'
#    yum: name=binutils state=present
#      - disablerepo='*'
#      - enablerepo='epel'
#      - update_cache
  async: 1000
  poll: 0
  register: yum_sleeper

- name: 'YUM - check on fire and forget task'
  async_status: jid={{ yum_sleeper.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 30

# vim: set filetype=ansible sts=2

