graylog_elasticsearch_discovery_zen_ping_unicast_hosts: '127.0.0.1:9300'
graylog_mongodb_uri:                                    'mongodb://mongo1:27017/graylog'
graylog_mongodb_max_connections:                        100
graylog_mongodb_threads_allowed_to_block_multiplier:    5

# graylog_es_debian_pin_version:     '5.*'

graylog_version: 2.3.1-rc1
graylog_install_elasticsearch: False
graylog_install_mongodb:       False
graylog_install_nginx:         True
graylog_install_java:          True

# General
graylog_is_master:            'True'
graylog_node_id_file:         '/etc/graylog/server/node-id'
graylog_password_secret:      '2jueVqZpwLLjaWxV'
graylog_root_username:        'admin'
graylog_root_password_sha2:   '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918'
graylog_plugin_dir:           '/usr/share/graylog-server/plugin'
graylog_root_email:           ''
graylog_root_timezone:        'UTC'
graylog_alert_check_interval: 60
graylog_disable_sigar:        'False'
